// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: group_rpc.proto

package server

import (
	"context"

	"server/im_group/group_rpc/internal/logic"
	"server/im_group/group_rpc/internal/svc"
	"server/im_group/group_rpc/types/group_rpc"
)

type GroupsServer struct {
	svcCtx *svc.ServiceContext
	group_rpc.UnimplementedGroupsServer
}

func NewGroupsServer(svcCtx *svc.ServiceContext) *GroupsServer {
	return &GroupsServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupsServer) IsInGroup(ctx context.Context, in *group_rpc.IsInGroupRequest) (*group_rpc.IsInGroupResponse, error) {
	l := logic.NewIsInGroupLogic(ctx, s.svcCtx)
	return l.IsInGroup(in)
}
