// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type UserInfoRequest struct {
}

type UserInfoResponse struct {
	UserID         uint   `json:"userID"`
	NickName       string `json:"nickName"`
	Abstract       string `json:"abstract"`
	Avatar         string `json:"avatar"`
	Role           int8   `json:"role"`
	RegisterSource string `json:"registerSource"`
}
