// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"server/im_file/file_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/file/:imageName",
				Handler: ImageShowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/file/file",
				Handler: FileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/file/image",
				Handler: ImageHandler(serverCtx),
			},
		},
	)
}
